# The length of the main chassis link
chassis_length: 0.5
# The distance between the centers wheels
wheel_base: 0.4
#  The thickness of the plate that forms the chassis
chassis_thickness: 0.1
# The radius of the wheels
wheel_radius: 0.1
# The width of the wheels
wheel_width: 0.04